---
- name: Remove Linux headers
  sudo: yes
  shell: "dpkg --list | awk '{ print $2 }' | grep '{{ item }}' | xargs apt-get -y purge"
  with_items: cleanbox["linux_headers"]

- name: Remove unused libraries
  sudo: yes
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    force: yes
  with_items: cleanbox["purge"]

- name: apt autoremove
  sudo: yes
  shell: "apt-get -y autoremove"

- name: apt clean
  sudo: yes
  shell: "apt-get -y clean"

- name: Remove files and directories
  sudo: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items: cleanbox["remove"]

- name: Remove password for vagrant user
  sudo: yes
  command: "passwd {{ ansible_user_id }} -d"

- name: Cleaning up
  sudo: yes
  shell: "{{ item }}"
  with_items:
    - "rm -rf VBoxGuestAdditions_*.iso VBoxGuestAdditions_*.iso.?"
    - "rm -f /tmp/chef*deb"
    - "dd if=/dev/zero of=/EMPTY bs=1M && sudo rm -rf /EMPTY || sudo rm -rf /EMPTY && sync && sync && sync"

- name: Empty files
  sudo: yes
  shell: "cat /dev/null > {{ item }}"
  with_items: cleanbox["empty"]
